'use client';
import {useEffect,useState} from 'react';
type Page='dashboard'|'conversazioni'|'prodotti'|'faq'|'assistente'|'impostazioni';
const starterProducts=['Mystery Box Virale','Takis Selection','Latiao Selection'];
const starterFaq=[['Chi gestisce la spedizione?','TikTok Shop e il corriere.'],['Posso scegliere gli snack?','Faremo il possibile se l’ordine non è ancora stato preparato.']];
export default function Dashboard(){
 const [page,setPage]=useState<Page>('dashboard'); const [products,setProducts]=useState(starterProducts); const [name,setName]=useState('');
 const [faqs,setFaqs]=useState(starterFaq); const [q,setQ]=useState(''); const [a,setA]=useState('');
 const [prompt,setPrompt]=useState('Sei l’assistente ufficiale di Indy Candy Shop. Rispondi sempre in italiano con tono cordiale, professionale ed empatico. Non inventare informazioni. Ricorda che le spedizioni sono gestite da TikTok Shop e dal corriere. Concludi sempre con: Per qualsiasi necessità o dubbio, restiamo a disposizione 😊');
 useEffect(()=>{const p=localStorage.getItem('assistly-products');const f=localStorage.getItem('assistly-faq');const pr=localStorage.getItem('assistly-prompt');if(p)setProducts(JSON.parse(p));if(f)setFaqs(JSON.parse(f));if(pr)setPrompt(pr)},[]);
 function addProduct(){if(!name.trim())return;const next=[...products,name.trim()];setProducts(next);localStorage.setItem('assistly-products',JSON.stringify(next));setName('')}
 function addFaq(){if(!q.trim()||!a.trim())return;const next=[...faqs,[q.trim(),a.trim()]];setFaqs(next);localStorage.setItem('assistly-faq',JSON.stringify(next));setQ('');setA('')}
 return <div className="app"><aside><div className="brand">Assistly <span>AI</span><small>Indy Candy Shop</small></div>{(['dashboard','conversazioni','prodotti','faq','assistente','impostazioni'] as Page[]).map(x=><button key={x} className={page===x?'active':''} onClick={()=>setPage(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}<div className="online">● Assistente operativo</div></aside><main><header><div><p>CLIENTE PILOTA</p><h1>{page[0].toUpperCase()+page.slice(1)}</h1></div><b>Indy Candy Shop</b></header>
 {page==='dashboard'&&<><div className="metrics"><Card label="Conversazioni oggi" value="28"/><Card label="Risposte AI" value="23"/><Card label="Passaggi operatore" value="5"/><Card label="Tempo risparmiato" value="2h 10m"/></div><section><h2>Ultime conversazioni</h2><Row title="Cliente TikTok Shop" text="Pacco consegnato ma non ricevuto" tag="Operatore"/><Row title="Cliente WhatsApp" text="Richiesta Takis nella box" tag="Risolta AI"/><Row title="Cliente TikTok Shop" text="Prodotto arrivato aperto" tag="Foto richiesta"/></section></>}
 {page==='conversazioni'&&<section><h2>Conversazioni clienti</h2><Row title="Martina" text="Il pacco risulta consegnato ma non è arrivato" tag="Alta priorità"/><Row title="Luca" text="Potete inserire più snack piccanti?" tag="AI attiva"/><Row title="Sara" text="Una confezione è arrivata aperta" tag="Operatore"/></section>}
 {page==='prodotti'&&<section><h2>Prodotti</h2><div className="inline"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome prodotto"/><button className="primary" onClick={addProduct}>Aggiungi</button></div>{products.map((p,i)=><div className="item" key={i}><b>{p}</b><span>Disponibile</span></div>)}</section>}
 {page==='faq'&&<div className="cols"><section><h2>FAQ</h2>{faqs.map((f,i)=><div className="faq" key={i}><b>{f[0]}</b><p>{f[1]}</p></div>)}</section><section><h2>Aggiungi FAQ</h2><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Domanda"/><textarea value={a} onChange={e=>setA(e.target.value)} placeholder="Risposta"/><button className="primary" onClick={addFaq}>Salva FAQ</button></section></div>}
 {page==='assistente'&&<section><h2>Configurazione Assistente AI</h2><div className="status">Indy Candy Assistant <span>Online</span></div><label>Istruzioni principali</label><textarea className="prompt" value={prompt} onChange={e=>setPrompt(e.target.value)}/><button className="primary" onClick={()=>{localStorage.setItem('assistly-prompt',prompt);alert('Istruzioni salvate')}}>Salva istruzioni</button></section>}
 {page==='impostazioni'&&<section><h2>Impostazioni azienda</h2><div className="grid"><label>Nome azienda<input defaultValue="Indy Candy Shop"/></label><label>Sede<input defaultValue="Provincia di Napoli"/></label><label>Canale principale<input defaultValue="TikTok Shop"/></label><label>WhatsApp<input defaultValue="Da collegare"/></label></div><div className="roadmap"><b>Prossime integrazioni</b><p>Database cloud, login, OpenAI, WhatsApp Business e multi-azienda.</p></div></section>}
 </main></div>}
function Card({label,value}:{label:string,value:string}){return <div className="card"><span>{label}</span><strong>{value}</strong></div>}
function Row({title,text,tag}:{title:string,text:string,tag:string}){return <div className="row"><div><b>{title}</b><p>{text}</p></div><span>{tag}</span></div>}
